name: pangeo
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - netcdf4
  - cfgrib
  - pydap
  - scipy
  - bottleneck
  - distributed
  - matplotlib
  - cartopy
  - seaborn
  - tqdm
  - pandas-profiling
  - jupyterlab
  - nodejs
  - eofs
  - spyder
  - pyviz::holoviews
  - pyviz::geoviews
  - pyviz::hvplot
  - intake
  - intake-xarray=0.3.1
  - pip
  - pip:
      - dask_labextension