name: pangeo
channels:
  - conda-forge
dependencies:
  - black
  - xarray
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - netcdf4
  - zarr
  - cfgrib
  - pydap
  - scipy
  - bottleneck
  - distributed
  - matplotlib
  - cartopy
  - descartes
  - geopandas
  - shapely
  - rasterio
  - seaborn
  - tqdm
  - pandas-profiling
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - eofs
  - spyder
  - pyviz::holoviews
  - pyviz::geoviews
  - pyviz::panel
  - pyviz::hvplot
  - scikit-learn
  - intake
  - intake-xarray=0.3.1
  - gcsfs
  - python-graphviz
  - graphviz
  - pip
  - pip:
      - dask_labextension
      - nbresuse
      - salem